services:
  postgres:
    image: postgres:16
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: aszender
      POSTGRES_PASSWORD: AszePass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  products-service:
    build:
      context: ./products-service
    container_name: products-service
    depends_on:
      - postgres
    environment:
      # Optional: override if you want a different port inside container
      - SERVER_PORT=8080
      # PostgreSQL connection (when running in Docker)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=aszender
      - SPRING_DATASOURCE_PASSWORD=AszePass
    expose:
      - "8080"

  nginx:
    image: nginx:1.27-alpine
    container_name: products-service-nginx
    depends_on:
      - products-service
    ports:
      # Public entrypoint: Nginx on host
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft combined mode (no ZooKeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Required for single-node Kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

volumes:
  postgres-data:
